"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import {
  Upload,
  X,
  Rocket,
  Monitor,
  LayoutGrid,
  Sparkles,
  CheckCircle2,
  Loader2,
  ImageIcon,
  Cpu,
  Home,
} from "lucide-react";

interface ImageAsset {
  id: string;
  file: File;
  url: string;
  name: string;
}

type LayoutMode = "immersive" | "proposal";

interface CompileStatus {
  isCompiling: boolean;
  currentStep: number;
  totalSteps: number;
  message: string;
  isComplete: boolean;
}

export default function PPTXEngine() {
  const [assets, setAssets] = useState<ImageAsset[]>([]);
  const [title, setTitle] = useState("");
  const [layoutMode, setLayoutMode] = useState<LayoutMode>("immersive");
  const [status, setStatus] = useState<CompileStatus>({
    isCompiling: false,
    currentStep: 0,
    totalSteps: 0,
    message: "",
    isComplete: false,
  });
  const [isDragOver, setIsDragOver] = useState(false);
  const [pptxReady, setPptxReady] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (typeof window !== "undefined" && (window as any).PptxGenJS) {
      setPptxReady(true);
    }
  }, []);

  const handleFiles = useCallback((files: FileList | null) => {
    if (!files) return;
    const imageFiles = Array.from(files).filter((file) =>
      file.type.startsWith("image/")
    );
    const newAssets: ImageAsset[] = imageFiles.map((file) => ({
      id: crypto.randomUUID(),
      file,
      url: URL.createObjectURL(file),
      name: file.name,
    }));
    setAssets((prev) => [...prev, ...newAssets]);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragOver(false);
      handleFiles(e.dataTransfer.files);
    },
    [handleFiles]
  );

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
  }, []);

  const removeAsset = useCallback((id: string) => {
    setAssets((prev) => {
      const asset = prev.find((a) => a.id === id);
      if (asset) URL.revokeObjectURL(asset.url);
      return prev.filter((a) => a.id !== id);
    });
  }, []);

  const processImage = async (
    asset: ImageAsset,
    index: number,
    total: number
  ): Promise<string> => {
    setStatus((prev) => ({
      ...prev,
      currentStep: index + 1,
      message: `[${index + 1}/${total}] 正在执行跨域图像解析与静默压缩...`,
    }));

    return new Promise((resolve, reject) => {
      const img = new Image();
      img.crossOrigin = "anonymous";

      img.onload = () => {
        try {
          const MAX_SIZE = 1920;
          let { width, height } = img;

          if (width > MAX_SIZE || height > MAX_SIZE) {
            const ratio = Math.min(MAX_SIZE / width, MAX_SIZE / height);
            width = Math.round(width * ratio);
            height = Math.round(height * ratio);
          }

          const canvas = document.createElement("canvas");
          canvas.width = width;
          canvas.height = height;
          const ctx = canvas.getContext("2d");

          if (!ctx) {
            reject(new Error("Canvas context unavailable"));
            return;
          }

          ctx.drawImage(img, 0, 0, width, height);
          const base64 = canvas.toDataURL("image/jpeg", 0.8);
          resolve(base64);
        } catch (error) {
          reject(error);
        }
      };

      img.onerror = () => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = () => reject(new Error("Failed to read image"));
        reader.readAsDataURL(asset.file);
      };

      img.src = asset.url;
    });
  };

  const compilePPTX = async () => {
    if (assets.length === 0 || !pptxReady) return;

    const pptxgen = (window as any).PptxGenJS;
    
    setStatus({
      isCompiling: true,
      currentStep: 0,
      totalSteps: assets.length + 2,
      message: "[0] 正在初始化 PPTX 编译引擎...",
      isComplete: false,
    });

    try {
      const pres = new pptxgen();
      pres.defineLayout({ name: "16x9", width: 10, height: 5.625 });
      pres.layout = "16x9";

      pres.author = "XiaomaAI Asset Engine";
      pres.title = title || "Asset Lookbook";
      pres.subject = "Generated by PPTX Compile Engine";

      await new Promise((r) => setTimeout(r, 300));

      const processedImages: string[] = [];
      for (let i = 0; i < assets.length; i++) {
        const base64 = await processImage(assets[i], i, assets.length);
        processedImages.push(base64);
        await new Promise((r) => setTimeout(r, 50));
      }

      setStatus((prev) => ({
        ...prev,
        currentStep: assets.length + 1,
        message: `[${assets.length + 1}/${prev.totalSteps}] 正在执行幻灯片排版渲染...`,
      }));

      if (layoutMode === "immersive") {
        for (let i = 0; i < processedImages.length; i++) {
          const slide = pres.addSlide();
          slide.background = { color: "0F172A" };

          slide.addImage({
            data: processedImages[i],
            x: 0,
            y: 0,
            w: "100%",
            h: "100%",
            sizing: { type: "contain", w: "100%", h: "100%" },
          });

          slide.addText(`${i + 1}`, {
            x: 9.3,
            y: 5.2,
            w: 0.5,
            h: 0.3,
            fontSize: 10,
            color: "64748B",
            fontFace: "Arial",
          });
        }
      } else {
        for (let i = 0; i < processedImages.length; i += 2) {
          const slide = pres.addSlide();
          slide.background = { color: "0F172A" };

          slide.addImage({
            data: processedImages[i],
            x: 0.2,
            y: 0.3,
            w: 4.6,
            h: 4.2,
            sizing: { type: "contain", w: 4.6, h: 4.2 },
          });

          if (i + 1 < processedImages.length) {
            slide.addImage({
              data: processedImages[i + 1],
              x: 5.2,
              y: 0.3,
              w: 4.6,
              h: 4.2,
              sizing: { type: "contain", w: 4.6, h: 4.2 },
            });
          }

          slide.addShape(pres.ShapeType.rect, {
            x: 0.2,
            y: 4.7,
            w: 9.6,
            h: 0.7,
            fill: { color: "1E293B" },
            line: { color: "334155", width: 0.5 },
          });

          slide.addText("标注区域 / Annotation Area", {
            x: 0.4,
            y: 4.85,
            w: 9.2,
            h: 0.4,
            fontSize: 10,
            color: "64748B",
            fontFace: "Arial",
          });
        }
      }

      await new Promise((r) => setTimeout(r, 200));

      setStatus((prev) => ({
        ...prev,
        currentStep: prev.totalSteps,
        message: `[${prev.totalSteps}/${prev.totalSteps}] 正在封装 PPTX 二进制流...`,
      }));

      await new Promise((r) => setTimeout(r, 300));

      await pres.writeFile({
        fileName: `XiaomaAI_Asset_Lookbook_${Date.now()}.pptx`,
      });

      setStatus((prev) => ({
        ...prev,
        isCompiling: false,
        isComplete: true,
        message: "编译完成！文件已保存至本地",
      }));

      setTimeout(() => {
        setStatus((prev) => ({ ...prev, isComplete: false, message: "" }));
      }, 4000);
    } catch (error) {
      console.error("[v0] PPTX compilation error:", error);
      setStatus({
        isCompiling: false,
        currentStep: 0,
        totalSteps: 0,
        message: `编译失败: ${error instanceof Error ? error.message : "Unknown error"}`,
        isComplete: false,
      });
    }
  };

  const progress =
    status.totalSteps > 0
      ? (status.currentStep / status.totalSteps) * 100
      : 0;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-6 md:p-8">
      <header className="mb-8">
        <div className="flex items-center justify-between">
          <div className="inline-flex items-center gap-3">
            <Cpu className="w-8 h-8 text-purple-500" />
            <div>
              <h1 className="text-2xl md:text-3xl font-light tracking-wider">
                <span className="text-purple-400">PPTX</span>
                <span className="text-slate-400 mx-2">/</span>
                <span className="text-cyan-400">编译引擎</span>
              </h1>
              <p className="text-slate-500 text-sm font-mono">
                HIGH-END ASSET PACKAGING ENGINE v2.0
              </p>
            </div>
          </div>
          <button
            onClick={() => window.location.href = '/'}
            className="flex items-center gap-2 px-3 py-1.5 bg-white/10 hover:bg-white/20 rounded-lg text-sm text-white transition-colors"
          >
            <Home className="w-4 h-4" />
            <span>返回主页</span>
          </button>
        </div>
      </header>

      <div className="max-w-5xl mx-auto space-y-6">
        <section className="border border-slate-800 rounded-lg bg-slate-900/30 overflow-hidden">
          <div className="px-4 py-3 border-b border-slate-800 flex items-center gap-2">
            <ImageIcon className="w-4 h-4 text-purple-500" />
            <h2 className="text-sm font-mono text-slate-400 uppercase tracking-wider">
              Asset Pool / 资产调度区
            </h2>
            {assets.length > 0 && (
              <span className="ml-auto text-xs font-mono text-cyan-500">
                {assets.length} 项资产已载入
              </span>
            )}
          </div>

          <div
            className={`m-4 border-2 border-dashed rounded-lg transition-all duration-300 ${
              isDragOver
                ? "border-purple-500 bg-purple-500/10"
                : "border-slate-700 hover:border-slate-600"
            }`}
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onClick={() => fileInputRef.current?.click()}
          >
            <div className="py-12 flex flex-col items-center justify-center cursor-pointer">
              <Upload
                className={`w-10 h-10 mb-3 transition-colors ${
                  isDragOver ? "text-purple-400" : "text-slate-600"
                }`}
              />
              <p className="text-slate-400 text-sm mb-1">
                拖拽或点击载入多幅图像资源
              </p>
              <p className="text-slate-600 text-xs font-mono">
                支持 JPG / PNG / WebP / GIF
              </p>
            </div>
            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept="image/*"
              className="hidden"
              onChange={(e) => handleFiles(e.target.files)}
            />
          </div>

          {assets.length > 0 && (
            <div className="px-4 pb-4">
              <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 gap-3">
                {assets.map((asset, index) => (
                  <div
                    key={asset.id}
                    className="group relative aspect-square bg-slate-800 rounded-md overflow-hidden border border-slate-700 hover:border-purple-500/50 transition-colors"
                  >
                    <img
                      src={asset.url}
                      alt={asset.name}
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute top-1.5 left-1.5 bg-slate-900/90 text-cyan-400 text-[10px] font-mono px-1.5 py-0.5 rounded">
                      {String(index + 1).padStart(2, "0")}
                    </div>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        removeAsset(asset.id);
                      }}
                      className="absolute top-1.5 right-1.5 w-5 h-5 bg-slate-900/90 hover:bg-red-500 text-slate-400 hover:text-white rounded flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}
        </section>

        <section className="border border-slate-800 rounded-lg bg-slate-900/30 overflow-hidden">
          <div className="px-4 py-3 border-b border-slate-800 flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-cyan-500" />
            <h2 className="text-sm font-mono text-slate-400 uppercase tracking-wider">
              Strategy Config / 排版策略控制台
            </h2>
          </div>

          <div className="p-4 space-y-5">
            <div>
              <label className="block text-xs font-mono text-slate-500 mb-2 uppercase">
                文档大标题
              </label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="输入 PPTX 封面标题..."
                className="w-full bg-slate-900 border-0 rounded-md px-4 py-3 text-slate-200 placeholder-slate-600 focus:ring-1 focus:ring-purple-500 transition-all font-light"
              />
            </div>

            <div>
              <label className="block text-xs font-mono text-slate-500 mb-3 uppercase">
                排版模式
              </label>
              <div className="grid grid-cols-2 gap-3">
                <button
                  onClick={() => setLayoutMode("immersive")}
                  className={`relative p-4 rounded-lg border transition-all text-left ${
                    layoutMode === "immersive"
                      ? "border-purple-500 bg-purple-500/10"
                      : "border-slate-700 hover:border-slate-600 bg-slate-900/50"
                  }`}
                >
                  {layoutMode === "immersive" && (
                    <div className="absolute inset-0 rounded-lg opacity-50" />
                  )}
                  <div className="relative z-10">
                    <div className="flex items-center gap-2 mb-2">
                      <Monitor
                        className={`w-5 h-5 ${
                          layoutMode === "immersive"
                            ? "text-purple-400"
                            : "text-slate-500"
                        }`}
                      />
                      <span
                        className={`font-medium ${
                          layoutMode === "immersive"
                            ? "text-purple-300"
                            : "text-slate-400"
                        }`}
                      >
                        沉浸模式
                      </span>
                    </div>
                    <p className="text-xs text-slate-500">
                      每页 1 图，全屏按比例自适应
                    </p>
                  </div>
                </button>

                <button
                  onClick={() => setLayoutMode("proposal")}
                  className={`relative p-4 rounded-lg border transition-all text-left ${
                    layoutMode === "proposal"
                      ? "border-cyan-500 bg-cyan-500/10"
                      : "border-slate-700 hover:border-slate-600 bg-slate-900/50"
                  }`}
                >
                  {layoutMode === "proposal" && (
                    <div
                      className="absolute inset-0 rounded-lg opacity-50"
                      style={{
                        background:
                          "linear-gradient(90deg, transparent, rgba(34, 211, 238, 0.4), transparent)",
                        backgroundSize: "200% 100%",
                        animation: "shimmer 3s linear infinite",
                      }}
                    />
                  )}
                  <div className="relative z-10">
                    <div className="flex items-center gap-2 mb-2">
                      <LayoutGrid
                        className={`w-5 h-5 ${
                          layoutMode === "proposal"
                            ? "text-cyan-400"
                            : "text-slate-500"
                        }`}
                      />
                      <span
                        className={`font-medium ${
                          layoutMode === "proposal"
                            ? "text-cyan-300"
                            : "text-slate-400"
                        }`}
                      >
                        提案模式
                      </span>
                    </div>
                    <p className="text-xs text-slate-500">
                      每页 2 图，左右并排，预留标注区
                    </p>
                  </div>
                </button>
              </div>
            </div>
          </div>
        </section>

        <section className="border border-slate-800 rounded-lg bg-slate-900/30 overflow-hidden">
          <div className="px-4 py-3 border-b border-slate-800 flex items-center gap-2">
            <Rocket className="w-4 h-4 text-purple-500" />
            <h2 className="text-sm font-mono text-slate-400 uppercase tracking-wider">
              Export & Status / 编译输出与状态监控
            </h2>
          </div>

          <div className="p-4 space-y-4">
            <button
              onClick={compilePPTX}
              disabled={assets.length === 0 || status.isCompiling || !pptxReady}
              className={`w-full py-4 rounded-lg font-medium transition-all flex items-center justify-center gap-3 ${
                assets.length === 0 || !pptxReady
                  ? "bg-slate-800 text-slate-600 cursor-not-allowed"
                  : status.isCompiling
                    ? "bg-purple-900/50 text-purple-300 cursor-wait"
                    : "bg-gradient-to-r from-purple-600 to-purple-500 hover:from-purple-500 hover:to-purple-400 text-white"
              }`}
            >
              {status.isCompiling ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  <span>编译引擎运行中...</span>
                </>
              ) : status.isComplete ? (
                <>
                  <CheckCircle2 className="w-5 h-5 text-green-400" />
                  <span>编译完成</span>
                </>
              ) : (
                <>
                  <Rocket className="w-5 h-5" />
                  <span>启动本地 PPTX 编译引擎</span>
                </>
              )}
            </button>

            {(status.isCompiling || status.message) && (
              <div className="bg-slate-900 rounded-lg border border-slate-800 p-4 space-y-3">
                {status.isCompiling && (
                  <div className="h-1.5 bg-slate-800 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-purple-500 to-cyan-500 transition-all duration-300 ease-out"
                      style={{ width: `${progress}%` }}
                    />
                  </div>
                )}

                <div
                  className={`flex items-center gap-2 text-sm font-mono ${
                    status.isComplete ? "text-green-400" : "text-slate-400"
                  }`}
                >
                  {status.isCompiling && (
                    <div className="w-2 h-2 bg-purple-500 rounded-full animate-pulse" />
                  )}
                  {status.isComplete && (
                    <CheckCircle2 className="w-4 h-4 text-green-400" />
                  )}
                  <span>{status.message}</span>
                </div>

                {status.isCompiling && (
                  <div className="flex items-center justify-between text-xs text-slate-600 font-mono">
                    <span>
                      进度: {status.currentStep}/{status.totalSteps}
                    </span>
                    <span>{Math.round(progress)}%</span>
                  </div>
                )}
              </div>
            )}

            {assets.length === 0 && !status.message && (
              <p className="text-center text-slate-600 text-sm py-2">
                请先在上方资产池载入图像资源
              </p>
            )}
          </div>
        </section>

        <footer className="text-center pt-4">
          <p className="text-slate-700 text-xs font-mono">
            PPTX COMPILE ENGINE • PURE CLIENT-SIDE • ZERO SERVER DEPENDENCY
          </p>
        </footer>
      </div>
    </div>
  );
}